server:
  port: 9001

spring:
  application:
    name: authorize-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arm?useSSL=true&userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: moeyui0624

logging:
  level:
    com.albert.godword.arm.mapper.*: trace
    org.springframework.security: debug
  file:
    path: .cata_log